apiVersion: v1
kind: ServiceAccount
metadata:
  name: bingsan
  labels:
    app: bingsan
    app.kubernetes.io/name: bingsan
    app.kubernetes.io/component: catalog
automountServiceAccountToken: false
